# Generated by Django 2.2.7 on 2020-01-17 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(default='', help_text='长网址', max_length=30, verbose_name='长网址')),
                ('short_url', models.CharField(default='', help_text='短网址', max_length=30, verbose_name='短网址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'URL集合',
                'verbose_name_plural': 'URL集合',
            },
        ),
    ]
