# Generated by Django 2.2.7 on 2020-01-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.CharField(default='', help_text='长网址', max_length=1000, verbose_name='长网址'),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='', help_text='短网址', max_length=10, verbose_name='短网址'),
        ),
    ]
