# Generated by Django 2.2.7 on 2020-01-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_auto_20200117_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='', help_text='短网址', max_length=100, verbose_name='短网址'),
        ),
    ]
